### ISSUE TITLE
SASpy issues

### ISSUE THREAD

**Issue by ChrisH-NZ** [emblsaxs/saspy#2]
I am having issues getting SASpy plugin to work on windows... I have installed Open Source Pymol and have the latest ATSAS 2.8.2. When I install the plugin and reopen Pymol and directed the error that appear is as follows: 

![saspy error](https://user-images.githubusercontent.com/34055158/33307692-939a1d86-d46b-11e7-893c-b5f15e13dfb5.png)

Due you have any suggestions as to what may be the issue? I have another version of PyMOL installed (education version). Otherwise im not sure what the issue is

Any help would be greatly appreciated as I would love to get this plugin working!

**Comment by apanjkovich** [comment]
Dear Chris,
please update PyMOL, the version you are using dates from 2006 and is not supported by SASpy. Any recent open source build (>1.7) or the new PyMOL 2.0 should work fine.
Best,
sasha
